### ISSUE TITLE
『叨扰』

### ISSUE THREAD

**Issue by alaskasquirrel** [booooodv/PodLetter#19]
[Email-newsletter-RSS](https://github.com/alaskasquirrel/Email-newsletter-RSS)&[Chinese-Podcasts](https://github.com/alaskasquirrel/Chinese-Podcasts) 虽说不少人关注，但是参与分享之人屈指可数，日常都是我个人在更新。
可否在〖Futurow 未来派〗分享呼吁一下。

**Comment by booooodv** [comment]
好呀好呀，我在 PR 里增加了两个项目的推荐，在 Newsletter 里也会提及，非常棒的项目，我以后也多多参与。

网站上已经能看到啦，因为没图标所以是默认的

![](https://myuppic-1256609062.cos.ap-beijing.myqcloud.com/2021/12/0420211204230217.png)
